<?xml version="1.0" encoding="utf-8"?>
<Database Name="PaymentsData" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.FXRate" Member="FXRate">
    <Type Name="FXRate">
      <Column Name="BaseCurrencyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TermsCurrencyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EndOfDayRate" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LedgerTransaction" Member="LedgerTransaction">
    <Type Name="LedgerTransaction">
      <Column Name="LedgerTransactionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LedgerTransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LedgerTransactionDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,6) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountOperatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>